name: Lint and test

on: pull_request

concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-linters:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '20.x'
      - run: npm install
      - run: npm run lint
      - run: npm run package